const TICKER_NAMES = {
  AAPL: "Apple Inc.",
  MSFT: "Microsoft",
  GOOGL: "Alphabet",
  GOOG: "Alphabet",
  AMZN: "Amazon",
  TSLA: "Tesla",
  NVDA: "NVIDIA",
  META: "Meta Platforms",
  NFLX: "Netflix",
  AMD: "AMD",
  INTC: "Intel",
  CRM: "Salesforce",
  ORCL: "Oracle",
  ADBE: "Adobe",
  PYPL: "PayPal",
  SQ: "Block Inc.",
  SHOP: "Shopify",
  SPOT: "Spotify",
  UBER: "Uber",
  LYFT: "Lyft",
  SNAP: "Snap Inc.",
  PINS: "Pinterest",
  ZM: "Zoom",
  PLTR: "Palantir",
  SOFI: "SoFi",
  HOOD: "Robinhood",
  COIN: "Coinbase",
  MARA: "Marathon Digital",
  RIOT: "Riot Platforms",
  SPY: "S&P 500 ETF",
  QQQ: "Nasdaq-100 ETF",
  IWM: "Russell 2000 ETF",
  DIA: "Dow Jones ETF",
  VTI: "Total Market ETF",
  VOO: "Vanguard S&P 500",
  ARKK: "ARK Innovation",
  XLF: "Financials ETF",
  XLE: "Energy ETF",
  XLK: "Tech ETF",
  GLD: "Gold ETF",
  SLV: "Silver ETF",
  JPM: "JPMorgan",
  BAC: "Bank of America",
  GS: "Goldman Sachs",
  MS: "Morgan Stanley",
  WFC: "Wells Fargo",
  V: "Visa",
  MA: "Mastercard",
  UNH: "UnitedHealth",
  JNJ: "Johnson & Johnson",
  PFE: "Pfizer",
  MRNA: "Moderna",
  ABBV: "AbbVie",
  LLY: "Eli Lilly",
  DIS: "Disney",
  BA: "Boeing",
  LMT: "Lockheed Martin",
  XOM: "Exxon Mobil",
  CVX: "Chevron",
  WMT: "Walmart",
  TGT: "Target",
  COST: "Costco",
  HD: "Home Depot",
  F: "Ford",
  GM: "General Motors",
  RIVN: "Rivian",
  LCID: "Lucid Motors",
  NIO: "NIO Inc.",
  BABA: "Alibaba",
  TSM: "TSMC",
  ASML: "ASML",
  AVGO: "Broadcom",
  MU: "Micron",
  QCOM: "Qualcomm",
  ABNB: "Airbnb",
  DASH: "DoorDash",
  RBLX: "Roblox",
  CRWD: "CrowdStrike",
  NET: "Cloudflare",
  DDOG: "Datadog",
  GME: "GameStop",
  AMC: "AMC Entertainment",
  BB: "BlackBerry",
  NOK: "Nokia",
  SMCI: "Super Micro",
  ARM: "Arm Holdings",
  MSTR: "MicroStrategy",
};

export function getCompanyName(ticker) {
  return TICKER_NAMES[ticker] || ticker;
}
